---
name: JDownloader
version: 1.1-alpha0
slug: jdownloader
description: Run JDownloader in Home Assistant
url: https://github.com/lamauny/hassio-addons
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - i386
map:
  - media:rw
  - share:rw
  - config:rw
ports:
  3129/tcp: 3129
ports_description:
  3129/tcp: MyJDownloader communication interface
options:
  device_name: "JDownloader2 - Home Assistant"
  email: "user@email.com"
  password: "password"
  log_level: info
schema:
  device_name: str
  email: str
  password: password
  cifsdomain: str?
  cifsusername: str?
  cifspassword: password?
  localdisks: str?
  networkdisks: str?
  smbv1: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
