---
name: JDownloader
version: 1.1-alpha6
slug: jdownloader
description: Run JDownloader in Home Assistant
url: https://github.com/lamauny/hassio-addons
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - i386
map:
  - media:rw
  - share:rw
  - config:rw
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
ports:
  3129/tcp: 3129
ports_description:
  3129/tcp: MyJDownloader communication interface
options:
  device_name: "JDownloader2 - Home Assistant"
  email: "user@email.com"
  password: "password"
  log_level: info
schema:
  device_name: str
  email: str
  password: password
  cifsusername: str?
  cifspassword: password?
  localdisks: str?
  networkdisks: str?
  smbv1: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
devices: 
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
