---
name: pyLoad
version: 0.1-alpha19
slug: pyload
description: Run pyLoad in Home Assistant
url: https://github.com/lamauny/hassio-addons
init: false
webui: "http://[HOST]:[PORT:8000]"
arch:
  - aarch64
  - amd64
  - armhf
map:
  - media:rw
  - share:rw
  - config:rw
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
ports:
  8000/tcp: 8000
  9666/tcp: 9666
ports_description:
  8000/tcp: pyLoad WebUI
  9666/tcp: Click'n'Load port
options:
  PGID: "1000"
  PUID: "1000"
  download_dir: "/share/downloads"
  log_level: info
schema:
  PGID: int?
  PUID: int?
  download_dir: str
  cifsusername: str?
  cifspassword: password?
  localdisks: str?
  networkdisks: str?
  smbv1: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
devices:
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
