arch:
- aarch64
- amd64
- armhf
- arm32v6
- arm64v8
- i386
codenotary: lamauny@chez.com
description: jDownloader server
hassio_api: true
host_network: true #
image: ghcr.io/jaymoulin/jdownloader
init: false
map:
- config:rw
name: JDownloader
options:
  user: user@email.com
  passwd: password
  config: Jdownloader/cfg
  extensions: Jdownloader/ext
  downloads: Jdownloader/Downloads
schema:
  address: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  3129/tcp: 3129
ports_description:
  3129/tcp: MyJDownloader communication interface
slug: jdownloader
startup: services
url: https://github.com/lamauny/hassio-addons/addon-jdownloader
version: 0.1.0
